name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@leexiaohui'

      - name: Configure npm auth (write .npmrc)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Using npm userconfig: $NPM_CONFIG_USERCONFIG"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "$NPM_CONFIG_USERCONFIG"

      - name: Verify npm auth & registry
        run: |
          echo "registry: $(npm config get registry)"
          npm whoami || echo "Not authenticated"
          npm view @leexiaohui/vframe-player version || echo "Package not found (first publish is expected)"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -r --filter ./packages/** run build

      - name: Copy LICENSE into all packages
        run: |
          if [ -f LICENSE ]; then
            for d in packages/*; do
              if [ -d "$d" ]; then
                cp LICENSE "$d/LICENSE" || true
              fi
            done
          fi

      - name: Changesets release
        uses: changesets/action@v1
        with:
          version: pnpm -w changeset version
          publish: pnpm -w changeset publish
          title: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
